 


isInArray(o13r1, lastmsg)==true?(smsg="<b>Notice of admission of case. </b><br>Any party to a suit may give notice by his or her pleading, or otherwise in writing, that he or she admits the truth of the whole or any part of the case of any other party."):
isInArray(o13r2, lastmsg)==true?(smsg="<b>Notice to admit documents.</b><br> Either party may call on the other to admit any document, saving all just exceptions; and, in case of refusal or neglect to admit, after the notice, the costs of proving any such document shall be paid by the party so neglecting or refusing, whatever the result of the suit may be, unless the court otherwise directs; and no costs of proving any document shall be allowed, unless the notice is given, except where the omission to give the notice is, in the opinion of the court, a saving of expense."):
isInArray(o13r3, lastmsg)==true?(smsg="<b>Form of notice.</b><br>A notice to admit documents shall be in Form 9 of Appendix B to these Rules, with such variations as circumstances may require."):
isInArray(o13r4, lastmsg)==true?(smsg="<b>Notice to admit facts.</b><br> Any party may, by notice in writing, at any time not later than nine days before the day fixed for the hearing, call on any other party to admit, for the purposes of the suit only, any specific fact mentioned in the notice, and in case of refusal or neglect to admit the fact within six days after service of the notice, or within such further time as may be allowed by the court, the cost of providing the fact shall be paid by the party so neglecting or refusing, whatever the result of the suit may be, unless the court otherwise directs; except that— <br>(a) any admission made, in pursuance of the notice is to be deemed to be made only for the purposes of the particular suit, and not as an admission to be used against the party on any other occasion or in favour of any person other than the party giving the notice; and <br>(b) the court may at any time allow any party to amend or withdraw any admission so made on such terms as may be just."):
isInArray(o13r5, lastmsg)==true?(smsg="<b>Form of admission.</b><br> A notice to admit facts shall be in Form 10 of Appendix B to these Rules, and an admission of facts shall be in Form 11 of Appendix B to these Rules, with such variations as circumstances may require."):
isInArray(o13r6, lastmsg)==true?(smsg="<b>Judgment on admissions.</b><br> Any party may at any stage of a suit, where an admission of facts has been made, either on the pleadings or otherwise, apply to the court for such judgment or order as upon the admission he or she may be entitled to, without waiting for the determination of any other question between the parties; and the court may upon the application make such order, or give such judgment, as the court may think just."):
isInArray(o13r7, lastmsg)==true?(smsg="<b>Affidavit of signature.</b><br>An affidavit of the advocate or his or her clerk of the due signature of any admissions made in pursuance of any notice to admit documents or facts shall be sufficient evidence of the admissions, if evidence of the admissions is required. "):
isInArray(o13r8, lastmsg)==true?(smsg="<b>Notice to produce documents in court.</b><br> (1) A notice to produce documents shall be in Form 12 of Appendix B to these Rules, with such variations as circumstances may require. <br>(2) An affidavit of the advocate or his or her clerk of the service of any notice to produce, and of the time when it was served, with a copy of the notice to produce, shall in all cases be sufficient evidence of the service of the notice and of the time when it was served."):
isInArray(o13r9, lastmsg)==true?(smsg="<b>Costs.</b><br> If a notice to admit or produce comprises documents which are not necessary, the costs occasioned by the notice shall be borne by the party giving the notice"):

isInArray(o14r1, lastmsg)==true?(smsg="<b>Endorsements on documents admitted in evidence. </b><br>(1) Subject to subrule (2) of this rule, there shall be endorsed on every document which has been admitted in evidence in the suit the following particulars— (a) the number and title of the suit; (b) the party producing the document; and (c) the date on which it was produced, and the endorsement shall be signed or initialled by an officer of the court.<br> (2) Where a document so admitted is an entry in a book, account or record, and a copy of the document has been substituted for the original under rule 2 of this Order, the particulars required by subrule (1) of this rule shall be endorsed on the copy, and the endorsement on the copy shall be signed or initialled by the judge or by an officer of the court under his or her direction."):
isInArray(o14r2, lastmsg)==true?(smsg="<b>Endorsements on copies of admitted entries in books, accounts and records.</b><br> (1) Except insofar as is otherwise provided by any law relating to the production in evidence of bankers’ books, where a document admitted in evidence in the suit is an entry in a letter book or a shop book or other account in current use, the party on whose behalf the book or account is produced may furnish a copy of the entry. <br>(2) Where the document admitted in evidence is an entry in a public record produced from a public office or by a public officer, or an entry in a book or account belonging to a person other than a party on whose behalf the book or account is produced, the court may require a copy of the entry to be furnished— <br>(a) where the record, book or account is produced on behalf of a party, then by that party; or <br>(b) where the record, book or account is produced in obedience to an order of the court acting of its own motion, then by either or any party. <br>(3) Where a copy of an entry is furnished under subrules (1) and (2) of this rule, the court shall, after causing the copy to be examined, compared and certified, mark the entry and cause the book, account or record in which it occurs to be returned to the person producing it; except that the court may accept, in the case of a copy of a public record, a certificate of correctness from the public officer in whose charge the record is."):
isInArray(o14r3, lastmsg)==true?(smsg="<b>Recording of admitted and return of rejected documents.</b><br> (1) Every document which has been admitted in evidence, or a copy of it where a copy has been substituted for the original under rule 2 of this Order, shall form part of the record of the suit.<br> (2) Documents not admitted in evidence shall not form part of the record, and shall be returned to the persons respectively producing them after they have been endorsed by the judge or officer of the court with the particulars mentioned in rule 1(1)(a), (b) and (c) of this Order, together with a statement of their having been rejected. "):
isInArray(o14r4, lastmsg)==true?(smsg="<b>Recording of admitted and return of rejected documents.</b><br>Notwithstanding anything hereinbefore contained, the court may, if it sees sufficient cause, direct any document or book produced before it in any suit to be impounded and kept in the custody of an officer of the court for such period and subject to such conditions as the court thinks fit."):
isInArray(o14r5, lastmsg)==true?(smsg="<b>Return of admitted documents.</b><br> (1) Any person, whether a party to the suit or not, desirous of receiving back any document produced by him or her in the suit and placed on the record, shall, unless the document is impounded under rule 4 of this Order, be entitled to receive back the document— <br>(a) when the suit has been disposed of, and, if the suit is one in which an appeal is allowed, where the time for filing an appeal has elapsed and no appeal has been filed; and<br> (b) if any appeal has been filed, when the appeal has been disposed of, except that—<br> (c) a document may be returned at any time earlier than that prescribed by this rule if the person applying for it delivers to the proper officer a certified copy to be substituted for the original and undertakes in writing to produce the original if required to do so; and<br> (d) no document shall be returned which, by force of the decree, has become wholly void or useless.<br> (2) On the return of a document admitted in evidence a receipt shall be given by the person receiving it."):
isInArray(o14r6, lastmsg)==true?(smsg="<b>Court may send for records of its own or of other court.</b><br> (1) The court may of its own motion, and may in its discretion upon the application of any of the parties to a suit, send for, either from its own records, or from any other court, the record of any other suit or proceeding and inspect the record. <br>(2) Every application made under this rule shall, unless the court otherwise directs, be supported by an affidavit showing how the record is material to the suit in which the application is made, and that the applicant cannot without unreasonable delay or expense obtain a duly authenticated copy of the record or of such portion of the record as the applicant requires, or that the production of the original is necessary for the purposes of justice.<br> (3) Nothing in this rule shall be deemed to enable the court to use in evidence any document which under the law of evidence would be inadmissible in the suit."):
isInArray(o14r7, lastmsg)==true?(smsg="<b>Provisions as to documents applied to material objects.</b><br> The provisions contained in this Order as to documents shall, so far as may be, apply to all other material objects producible as evidence."):
isInArray(o14r8, lastmsg)==true?(smsg="<b>Procedure under this Order.</b><br>Applications under rule 6 of this Order shall be by summons in chambers."):

isInArray(o15r1, lastmsg)==true?(smsg="<b>Framing of issues.</b><br> (1) Issues arise when a material proposition of law or fact is affirmed by the one party and denied by the other. <br>(2) Material propositions are those propositions of law or fact which a plaintiff must allege in order to show a right to sue or a defendant must allege in order to constitute a defence. <br>(3) Each material proposition affirmed by one party and denied by the other shall form the subject of a distinct issue. <br>(4) Issues are of two kinds: issues of law and issues of fact. <br>(5) At the hearing of the suit the court shall, after reading the pleadings, if any, and after such examination of the parties or their advocates as may appear necessary, ascertain upon what material propositions of law or fact the parties are at variance, and shall thereupon proceed to frame and record the issues on which the right decision of the case appears to depend.<br> (6) Nothing in this rule requires the court to frame and record issues where the defendant at the hearing of the suit makes no defence, or where issue has been joined upon the pleadings."):
isInArray(o15r2, lastmsg)==true?(smsg="<b>Issues of law and issues of fact.</b><br> Where issues both of law and of fact arise in the same suit, and the court is of opinion that the case or any part of it may be disposed of on the issues of law only, it shall try those issues first, and for that purpose may, if it thinks fit, postpone the settlement of the issues of fact until after the issues of law have been determined. "):
isInArray(o15r3, lastmsg)==true?(smsg="<b>Materials from which issues may be framed. </b><br>The court may frame the issues from all or any of the following materials—<br> (a) allegations made on oath by the parties, or by any persons present on their behalf, or made by the advocates of the parties;<br> (b) allegations made in the pleadings or in answers to interrogatories delivered in the suit; and <br>(c) the contents of documents produced by either party."):
isInArray(o15r4, lastmsg)==true?(smsg="<b>Court may examine witnesses or documents before framing issues.</b><br> Where the court is of opinion that the issues cannot be correctly framed without the examination of some person not before the court, or without the inspection of some document not produced in the suit, it may adjourn the framing of the issues to a future day, and may, subject to any law for the time being in force, compel the attendance of any person, or the production of any document by the person in whose possession or power it is, by summons or other process."):
isInArray(o15r5, lastmsg)==true?(smsg="<b>Power to amend and strike out issues. </b><br>(1) The court may at any time before passing a decree amend the issues or frame additional issues on such terms as it thinks fit, and all such amendments or additional issues as may be necessary for determining the matters in controversy between the parties shall be so made or framed. <br>(2) The court may also at any time before passing a decree strike out any issues that appear to it to be wrongly framed or introduced."):
isInArray(o15r6, lastmsg)==true?(smsg="<b>Questions of law or fact may by agreement be stated in the form of issues.</b><br> Where the parties to a suit are agreed as to the question of law or of fact to be decided between them, they may state the question in the form of an issue and enter into an agreement in writing that, upon the finding of the court in the affirmative or the negative of the issue— <br>(a) a sum of money specified in the agreement, or to be ascertained by the court or in such manner as the court may direct, shall be paid by one of the parties to the other of them, or that one of them be declared entitled to some right or subject to some liability specified in the agreement;<br> (b) some property specified in the agreement and in dispute in the suit shall be delivered by one of the parties to the other of them, or as that other may direct; or<br> (c) one or more of the parties shall do or abstain from doing some particular act in the agreement and relating to the matter in dispute."):
isInArray(o15r7, lastmsg)==true?(smsg="<b>Court, if satisfied that agreement was executed in good faith, may pronounce judgment.</b><br> Where the court is satisfied, after making such inquiry as it deems proper—<br> (a) that the agreement was duly executed by the parties; <br>(b) that they have a substantial interest in the decision of the question as aforesaid; and <br>(c) that the question is fit to be tried and decided, it shall proceed to record and try the issue and state its finding or decision on the issue in the same manner as if the issue had been framed by the court; and shall, upon the finding or decision of the issue, pronounce judgment according to the terms of the agreement; and upon the judgment so pronounced a decree shall follow. "):
